POST http://localhost:8080/account
Content-Type: application/json

{
  "accountName": "Saving",
  "accountNumber": "1000121200005",
  "currency": "TZS",
  "balance": 0.49,
  "accountType": "Saving",
  "userId": "9"
}

###
PUT http://localhost:8080/account
Content-Type: application/json

{
  "id": 15,
  "accountName": "Main Account",
  "accountNumber": "1000121200003",
  "currency": "TZS",
  "balance": 0.49,
  "accountType": "Currency",
  "userId": "8"
}

###

GET http://localhost:8080/account

###

GET http://localhost:8080/account/15

